// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmvzwbmMSDYOGMWGl6bgXYOAsnl9clSKc',
    appId: '1:451802617054:web:35dd6afb746e8808369e4f',
    messagingSenderId: '451802617054',
    projectId: 'crudmahasiswa-b209e',
    authDomain: 'crudmahasiswa-b209e.firebaseapp.com',
    storageBucket: 'crudmahasiswa-b209e.firebasestorage.app',
    measurementId: 'G-JK5EQ8S28G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9hbZNkrVy0ulEEOVpLAuRgjB4PXA0P8Y',
    appId: '1:451802617054:android:ba34c879bfea19d9369e4f',
    messagingSenderId: '451802617054',
    projectId: 'crudmahasiswa-b209e',
    storageBucket: 'crudmahasiswa-b209e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVz3RHKqk49gYx-D-EpeU8XzdVqBYnCOs',
    appId: '1:451802617054:ios:bc7cd62882a5e9d4369e4f',
    messagingSenderId: '451802617054',
    projectId: 'crudmahasiswa-b209e',
    storageBucket: 'crudmahasiswa-b209e.firebasestorage.app',
    iosBundleId: 'com.example.mahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVz3RHKqk49gYx-D-EpeU8XzdVqBYnCOs',
    appId: '1:451802617054:ios:bc7cd62882a5e9d4369e4f',
    messagingSenderId: '451802617054',
    projectId: 'crudmahasiswa-b209e',
    storageBucket: 'crudmahasiswa-b209e.firebasestorage.app',
    iosBundleId: 'com.example.mahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmvzwbmMSDYOGMWGl6bgXYOAsnl9clSKc',
    appId: '1:451802617054:web:ba26d9e62e1e2925369e4f',
    messagingSenderId: '451802617054',
    projectId: 'crudmahasiswa-b209e',
    authDomain: 'crudmahasiswa-b209e.firebaseapp.com',
    storageBucket: 'crudmahasiswa-b209e.firebasestorage.app',
    measurementId: 'G-8T50XCZMPJ',
  );
}
